version: '3.7'
services:
  invest-guru-db:
    image: postgres
    restart: always
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: investguru
      POSTGRES_PASSWORD: investguru
      ANON: web_anon
      AUTHENTICATOR: authenticator
  invest-guru-redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
    driver: local