version: '3.7'
services:
  invest-guru-db:
    image: postgres
    restart: always
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/0001-initialization.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: investguru
      POSTGRES_PASSWORD: investguru
      ANON: web_anon
      AUTHENTICATOR: authenticator
  invest-guru:
    depends_on:
      - invest-guru-db
    image: com.pintailconsultingllc/investguru
    restart: always
    ports:
      - 8080:8080
    environment:
      JDBC_URL: jdbc:postgresql://invest-guru-db:5432/investguru

volumes:
  db-data:
    driver: local